branches:
  only:
  - "/^v0.*$/"
  - master
language: python
python:
- '3.5'
cache: pip
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements.txt
sudo: required 
dist: trusty 
group: deprecated-2017Q4
addons:
  postgresql: '9.4'
before_script:
- mv configs/settings_deployment_test.py councilmatic/settings_deployment.py
script: python manage.py migrate
deploy:
  - provider: codedeploy
    access_key_id: AKIAJNYGDLOJKHOUWCAA
    secret_access_key:
      secure: XwYvq3lcX+IBilzN5vDWWKNbcsPy9g/ogzwZazA4MYDsZ4El2WHr4sKsdA66dhCnnaNcWIgVGh8lOsp7MtXulM5YVNfAY462S29cS/4N+nzQV/92vNi9XmrfkC2ioQXfrLSA+4Iq4lQbVasYpg15Tr3UaWnf+uxKlN6qRZ4XawUHNuXv5dPxJKBtqIvZJnBrO8elMiz85PvZQbPme5Vb4sMLm0S4PrP/vy5z2JNMdxqr4870Xc+rvF0NWAARJZycYs6LkpTZW8uWeVXk8V8IfQfJcgU0T5FrzIKSoBNWt4qUQyJLwhVk7bXmzKC+rp0P/VeysPuE6nFZpEltdOcxmX+2e/GQAgFQAMuQL9btavNDh1tyc0+u2jzI4RLlmgDr6Rble2jiw+tEcflCwcfmQqr8Kt2itHCgcIerI5VzpSQ1DL+iC5xgDeUtuIrN6bax/AYcQ/5etWVXEV1mWUzj6oAaP/X91AiSPt7ebQKprcaoxZ5IAkFD1XW8NX4c7oKHOz+bhzTgnJGZtE/XgoC6jZDzhUrlmjH/sq4bRJCtr3aXLBZX6MWz1AzYKg54lLI2EHOG6uOXsp/Pd4dCyLAQ+m8EJdNefaqK+x2CRJT4qZw1iG+KcekHRFKDFUjf1kYdoO1wwJe3LhPMYJv/JZCEq8yKD5QRJ6NFHMByWQiWzeI=
    application: nyc-councilmatic
    deployment_group: staging
    on:
      branch: master
  - provider: codedeploy
    access_key_id: AKIAJNYGDLOJKHOUWCAA
    secret_access_key:
      secure: XwYvq3lcX+IBilzN5vDWWKNbcsPy9g/ogzwZazA4MYDsZ4El2WHr4sKsdA66dhCnnaNcWIgVGh8lOsp7MtXulM5YVNfAY462S29cS/4N+nzQV/92vNi9XmrfkC2ioQXfrLSA+4Iq4lQbVasYpg15Tr3UaWnf+uxKlN6qRZ4XawUHNuXv5dPxJKBtqIvZJnBrO8elMiz85PvZQbPme5Vb4sMLm0S4PrP/vy5z2JNMdxqr4870Xc+rvF0NWAARJZycYs6LkpTZW8uWeVXk8V8IfQfJcgU0T5FrzIKSoBNWt4qUQyJLwhVk7bXmzKC+rp0P/VeysPuE6nFZpEltdOcxmX+2e/GQAgFQAMuQL9btavNDh1tyc0+u2jzI4RLlmgDr6Rble2jiw+tEcflCwcfmQqr8Kt2itHCgcIerI5VzpSQ1DL+iC5xgDeUtuIrN6bax/AYcQ/5etWVXEV1mWUzj6oAaP/X91AiSPt7ebQKprcaoxZ5IAkFD1XW8NX4c7oKHOz+bhzTgnJGZtE/XgoC6jZDzhUrlmjH/sq4bRJCtr3aXLBZX6MWz1AzYKg54lLI2EHOG6uOXsp/Pd4dCyLAQ+m8EJdNefaqK+x2CRJT4qZw1iG+KcekHRFKDFUjf1kYdoO1wwJe3LhPMYJv/JZCEq8yKD5QRJ6NFHMByWQiWzeI=
    application: nyc-councilmatic
    deployment_group: production
    on:
      tags: true
